const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'docs/phase4');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const before=read(path.join(dir,'before-metadata.json')),model=read(path.join(root,'docs/phase3/schema-catalog.json'));
let md='# Phase 4 — database analysis before implementation\n\nCaptured: '+before.captured_at+'. Catalog-only read-only queries; no student/customer/patient records exported. Official Board source schema is not connected and must not be inferred from the dummy model.\n\n';
md+='| Server/container | Actual database | PostgreSQL | Schemas | Base tables | pgvector available |\n| --- | --- | --- | --- | --- | --- |\n';
for(const r of before.records)md+=`| ${r.container} | ${r.database} | ${r.version} | ${(r.schemas||[]).join(', ')} | ${(r.tables||[]).length} | ${r.vector_available} |\n`;
md+='\nProposed target databases present before implementation: '+model.databases.filter(d=>before.development_databases.includes(d.name)).map(d=>d.name).join(', ')+' (blank means none). Four new application DBs belong only to the isolated development server. Existing Evolution internal DBs, n8n storage and the unrelated n8n-automation container are not migration targets.\n\n';
md+='## BISE business concept mapping\n\n“Not available” means actual Board table/column/type/nullability could not be inspected. Proposed fields below belong to our future synthetic model, NOT an official Board schema. Student/examination tables are Phase 8 scope, not Phase 4 foundational tables.\n\n| Business concept | Actual table | Actual column | Actual type / nullable | Proposed synthetic field | Proposed type / nullable | Notes |\n| --- | --- | --- | --- | --- | --- | --- |\n';
const mappings=[['Student ID','bise.students.id','uuid / no','Composite identity includes business_id'],['Student Name','bise.students.display_name','text / no','Protected field'],['Roll Number','bise.registrations.roll_number','text / no','Unique per business/exam; preserve leading zeros'],['B-Form/CNIC','No raw identifier field in current catalog','Not yet designed','Protected verifier adapter; matching identifiers alone does not authenticate; keyed fingerprint/encrypted storage only if approved'],['Exam','bise.exams.exam_code; year; session; attempt','See Phase 3 dictionary','Registration references exam_id; exam context required'],['Subject','bise.subject_marks.subject_code; subject_name; component','text / no','Theory/practical distinguished'],['Obtained Marks','bise.subject_marks.obtained_marks; bise.results.obtained_marks','numeric / yes','Null/withheld is not zero'],['Total Marks','bise.subject_marks.total_marks; bise.results.total_marks','numeric / yes','Source authoritative'],['Grade','bise.results.grade; bise.subject_marks.grade','text / yes','Source-issued grade; no guessed computation']];
for(const row of mappings)md+=`| ${row[0]} | Not available | Not available | Not available | ${row[1]} | ${row[2]} | ${row[3]} |\n`;
md+='\n## Recommended Phase 4 columns / keys by database\n\n16 foundational business tables; per-database migration bookkeeping is additional. Owner/runtime roles are separate. business_id is required on business-owned child rows; businesses.id is the tenant key. Domain configuration projections omit credential_ref. Configuration sync workers are not enabled by creating their tables.\n\n';
for(const db of model.databases){md+=`### ${db.name}\n\n`;for(const t of model.tables.filter(t=>t.database===db.name&&t.phase===4)){md+=`#### ${t.template}\n\n${t.purpose}\n\nPrimary key: (${t.primaryKey.join(', ')}).\n\n| Column | Proposed type | Nullable |\n| --- | --- | --- |\n`;for(const [name,c]of Object.entries(t.columns))md+=`| ${name} | ${c.type} | ${c.nullable?'yes':'no'} |\n`;for(const u of t.unique)md+=`\nUnique: (${u.join(', ')}).\n`;for(const f of t.foreignKeys)md+=`\nFK (${f.columns.join(', ')}) → ${f.target} (${f.targetColumns.join(', ')}).\n`;md+='\n';}}
md+='## Actual existing columns and primary keys (before migration)\n\n';
for(const r of before.records){md+=`### ${r.container} / ${r.database}\n\n`;if(!(r.tables||[]).length){md+='No application base tables.\n\n';continue;}md+='| Schema.table | Column | Actual type | Nullable |\n| --- | --- | --- | --- |\n';for(const c of r.columns||[])md+=`| ${c.schema}.${c.table} | ${c.column} | ${c.type} (${c.udt}) | ${c.nullable} |\n`;md+='\nPrimary keys:\n\n';for(const c of (r.constraints||[]).filter(c=>c.type==='p'))md+=`- ${c.schema}.${c.table}: ${c.definition}.\n`;md+='\n';}
md+='## Implementation gates\n\nPostgreSQL 15 compatibility is required; pgvector is deliberately deferred to Phase 12. Phase 4 does not create student/results, orders, appointments or knowledge tables. Runtime roles cannot own tables, bypass RLS, do DDL, edit configuration, or update/delete audit. Tenant context is supplied by trusted service code; raw SQL access is not a public authentication interface. Real verifier storage, Board mapping and full application authorization remain later feature gates.\n';
fs.writeFileSync(path.join(dir,'DATABASE_ANALYSIS_REPORT.md'),md);console.log('Database analysis report generated from actual pre-implementation metadata and separately labeled proposed catalog.');
