services:
  evolution-go:
    image: evoapicloud/evolution-go:latest
    container_name: evolution-go
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      # Server
      SERVER_PORT: 4000
      CLIENT_NAME: "evolution"

      GLOBAL_API_KEY: "429683C4C977415CAAFCCE10F7D57E11"

      # Databases
      POSTGRES_AUTH_DB: "postgresql://postgres:postgres@postgres:5432/evogo_auth?sslmode=disable"
      POSTGRES_USERS_DB: "postgresql://postgres:postgres@postgres:5432/evogo_users?sslmode=disable"
      DATABASE_SAVE_MESSAGES: "true"

      # Logs
      WADEBUG: "DEBUG"
      LOGTYPE: "console"
      LOG_DIRECTORY: "/app/logs"
      LOG_MAX_SIZE: "100"
      LOG_MAX_BACKUPS: "5"
      LOG_MAX_AGE: "30"
      LOG_COMPRESS: "true"

      # Connection
      CONNECT_ON_STARTUP: "false"
      WEBHOOK_FILES: "true"
      OS_NAME: "Linux"

      # Webhook (Direct internal container endpoint to n8n)
      WEBHOOK_URL: "http://n8n:5678/webhook/evolution-whatsapp-agent"

      # Disabled unused brokers
      AMQP_URL: ""
      AMQP_GLOBAL_ENABLED: "false"
      NATS_URL: ""
      NATS_GLOBAL_ENABLED: "false"
      MINIO_ENABLED: "false"

      # Events
      EVENT_IGNORE_GROUP: "false"
      EVENT_IGNORE_STATUS: "true"
      QRCODE_MAX_COUNT: "5"

    volumes:
      - evolution_data:/app/dbdata
      - evolution_logs:/app/logs
    networks:
      - evolution_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: evolution-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - evolution_network

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-automation
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Karachi
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - evolution_network

volumes:
  evolution_data:
    driver: local
  evolution_logs:
    driver: local
  postgres_data:
    driver: local
  n8n_data:
    driver: local

networks:
  evolution_network:
    driver: bridge